default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 1234567890
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: doantotnghiep

test:
  <<: *default
  database: doantotnghiep

production:
  <<: *default
  database: doantotnghiep
  username: son
  password: <%= ENV["FAQ_DATABASE_PASSWORD"] %>
